name: Test Cases
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  test:
    name: Test Cases
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['16.x']
        firefox-version: ['latest']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix['node-version'] }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}

      # ... (other steps for the test job)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./tests/coverage

  if_merged:
    name: Refresh Docs
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Print Message
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          curl https://afbot.b-bowler13.workers.dev/refreshDocs?pr_number=${PR_NUMBER}
