name: Refresh Docs
on:
  pull_request:
    types:
      - closed
    branches:
      - master
    push:
      - 'docs/**'


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        PR_NUMBER="${{ github.event.pull_request.number }}"
        curl https://afbot.auspres33.workers.dev/refresh-docs?pr_number=${PR_NUMBER}